# 补充

- 不够，关于 traceback 的仔细补充下。



# 异常的输出格式

举例：

```python
import traceback

print('########################################################')
print("1/0 Exception Info")
print('---------------------------------------------------------')
try:
    1 / 0
except Exception as e:
    print('str(Exception):\t', str(Exception))
    print('str(e):\t\t', str(e))
    print('repr(e):\t', repr(e))
    print('traceback.format_exc():\n%s' % traceback.format_exc())
print('########################################################')
print('\n########################################################')
print("i = int('a') Exception Info")
print('---------------------------------------------------------')
try:
    i = int('a')
except Exception as e:
    print('str(Exception):\t', str(Exception))
    print('str(e):\t\t', str(e))
    print('repr(e):\t', repr(e))
    print('traceback.format_exc():\n%s' % traceback.format_exc())
print('########################################################')

```

输出：

```
########################################################
1/0 Exception Info
---------------------------------------------------------
str(Exception):	 <class 'Exception'>
str(e):		 division by zero
repr(e):	 ZeroDivisionError('division by zero')
traceback.format_exc():
Traceback (most recent call last):
  File "D:/21.Practice/demo/d.py", line 7, in <module>
    1 / 0
ZeroDivisionError: division by zero

########################################################

########################################################
i = int('a') Exception Info
---------------------------------------------------------
str(Exception):	 <class 'Exception'>
str(e):		 invalid literal for int() with base 10: 'a'
repr(e):	 ValueError("invalid literal for int() with base 10: 'a'")
traceback.format_exc():
Traceback (most recent call last):
  File "D:/21.Practice/demo/d.py", line 18, in <module>
    i = int('a')
ValueError: invalid literal for int() with base 10: 'a'

########################################################
```

